# Generated by Django 5.2.5 on 2025-09-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_description_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
