# Generated by Django 5.2.5 on 2025-09-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_current_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_logout_required',
            field=models.BooleanField(default=False),
        ),
    ]
