# Generated by Django 5.2.5 on 2025-09-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='knowledge_docs/')),
                ('domain', models.CharField(choices=[('journal', 'Journal Coach'), ('mindset', 'Mindset Coach'), ('general', 'General Chatbot'), ('therapy', 'Challenge Therapy'), ('all', 'All Chatbots')], default='all', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
