# Generated by Django 5.2.5 on 2025-08-16 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_point_type', models.CharField(choices=[('positive_trigger', 'Positive Trigger'), ('negative_trigger', 'Negative Trigger'), ('recurring_thought', 'Recurring Thought'), ('future_goal', 'Future Goal'), ('milestone_gratitude', 'Milestone Gratitude')], max_length=50)),
                ('entry_point_description', models.TextField(blank=True, null=True)),
                ('layer1_facts', models.TextField(blank=True, null=True)),
                ('layer2_emotions', models.TextField(blank=True, null=True)),
                ('layer3_beliefs', models.TextField(blank=True, null=True)),
                ('perspective_expansion', models.TextField(blank=True, null=True)),
                ('value_connection', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
