# Generated by Django 5.2.5 on 2025-08-26 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_data', models.JSONField(default=dict)),
                ('conversation_history', models.JSONField(default=list)),
                ('current_phase', models.CharField(max_length=50)),
                ('challenge_type', models.CharField(max_length=50)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
