# Generated by Django 5.2.5 on 2025-08-28 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesession',
            name='session_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='challengesession',
            name='challenge_type',
            field=models.CharField(default='General Challenge', max_length=50),
        ),
    ]
