# Generated by Django 5.2.5 on 2025-09-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_challenge', '0002_challengesession_session_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesession',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
