# Generated by Django 5.2.5 on 2025-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('darkly', 'Darkly'), ('flatly', 'Flatly'), ('cerulean', 'Cerulean'), ('slate', 'Slate'), ('journal', 'Journal')], default='darkly', max_length=50)),
            ],
        ),
    ]
