# Generated by Django 5.2.5 on 2025-09-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chatsession_chatmessage_delete_redischatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
