# Generated by Django 5.2.5 on 2025-10-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chatsession_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_chat_history', models.BooleanField(default=True, help_text='If disabled, users cannot save chat history regardless of their preference')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
            },
        ),
    ]
