# Generated by Django 5.2.5 on 2025-08-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_history_chatsession_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
