# Generated by Django 5.2.5 on 2025-08-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='role',
            field=models.CharField(default='manager', max_length=50),
            preserve_default=False,
        ),
    ]
