# Generated by Django 5.2.5 on 2025-10-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='default name', max_length=100),
            preserve_default=False,
        ),
    ]
